name: Verify builds

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download dependencies
      run: go mod download

    - name: Create protoc-gen-ship
      run: make bin/protoc-gen-ship
